import React from "react";

const SingleData = {
    communityHeroHeading: 'Meet some of the taxly community',
    communityHeroSubHeading: 'From writers, interns and bakers, tech guys to investors, each of them has a story to tell.',
    communityHeroBtnText: 'Get started',
};

const CommunityStorySectionData = [{
        id: "1",
        personName: 'Alessio, Zurich',
        popupText: 'Read my story',
        cplName: 'Alessio',
        cplCityAndLanguage: 'Zurich, Swiss',
        cplH2One: 'What comes to mind when you hear the word tax?',
        cplpOne: 'Costly and timely.',
        cplH2Two: 'How did you do your taxes before?',
        cplpTwo: 'With an accountant.',
        cplH2Three: 'How was your experience with Taxly?',
        cplpThree: 'Actually I didn’t realise it could be done so fast.',
        cplH2Four: 'Were you skeptical about taxly in the beginning?',
        cplpFour: 'Yeah, a friend told me about taxly and I was intrigued by the price.',
        cplH2Five: 'What was your favorite thing about Taxly?',
        cplpFive: 'That it took about the same time it takes to cook some pasta.',
        cplH2Six: 'Would you recommend Taxly to a friend?',
        cplpSix: '100%.',
    },
    {
        id: "2",
        personName: 'Charlotte, St. Gallen',
        popupText: 'Read my story',
        cplName: 'Charlotte',
        cplCityAndLanguage: 'St. Gallen, Swiss',
        cplH2One: 'What comes to mind when you hear the word tax?',
        cplpOne: 'Being broke.',
        cplH2Two: 'How did you do your taxes before?',
        cplpTwo: 'On my own.',
        cplH2Three: 'How was your experience with Taxly?',
        cplpThree: 'Really easy and a surprisingly pleasant experience.',
        cplH2Four: 'Were you skeptical about taxly in the beginning?',
        cplpFour: 'I was more surprised this hasn’t been done before.',
        cplH2Five: 'What was your favorite thing about Taxly?',
        cplpFive: 'How easy it was.',
        cplH2Six: 'Would you recommend Taxly to a friend?',
        cplpSix: 'Already did',
        cplpEmoji: true,
    },
    {
        id: "3",
        personName: 'Maximilian, Zurich',
        popupText: 'Read my story',
        cplName: 'Maximilian',
        cplCityAndLanguage: 'Zurich, German',
        cplH2One: 'What comes to mind when you hear the word tax?',
        cplpOne: 'How much it’s going to cost me.',
        cplH2Two: 'How did you do your taxes before?',
        cplpTwo: 'I paid for an accountant.',
        cplH2Three: 'How was your experience with Taxly?',
        cplpThree: 'Yeah it was good. I didn’t realise it could be done so quick. And for 25 CHF. ',
        cplH2Four: 'Were you skeptical about taxly in the beginning?',
        cplpFour: 'A bit yes.',
        cplH2Five: 'What was your favorite thing about Taxly?',
        cplpFive: 'The price.',
        cplH2Six: 'Would you recommend Taxly to a friend?',
        cplpSix: 'Two of my friends already submitted with Taxly.',
    },
    {
        id: "4",
        personName: 'Emma, Basel Land',
        popupText: 'Read my story',
        cplName: 'Emma',
        cplCityAndLanguage: 'Basel Land, Swiss',
        cplH2One: 'What comes to mind when you hear the word tax?',
        cplpOne: 'Stress, time, money and the need for alcohol.',
        cplH2Two: 'How did you do your taxes before?',
        cplpTwo: 'I tried to do them by myself and then got my dad to check it.',
        cplH2Three: 'How was your experience with Taxly?',
        cplpThree: 'Was great. Finally don’t have to ask my dad for his help.',
        cplH2Four: 'Were you skeptical about taxly in the beginning?',
        cplpFour: 'A little, but the roger character seemed to know what he was doing.',
        cplH2Five: 'What was your favorite thing about Taxly?',
        cplpFive: 'How quick it was and that I can see the official tax return at the end.',
        cplH2Six: 'Would you recommend Taxly to a friend?',
        cplpSix: 'Yes, most defiantly.',
    },
    {
        id: "5",
        personName: 'Alex, Zurich',
        popupText: 'Read my story',
        cplName: 'Alex',
        cplCityAndLanguage: 'Zurich, English',
        cplH2One: 'What comes to mind when you hear the word tax?',
        cplpOne: 'Not much.',
        cplH2Two: 'How did you do your taxes before?',
        cplpTwo: 'In the UK its all deducted on your salary. So no bother really.',
        cplH2Three: 'How was your experience with Taxly?',
        cplpThree: 'Super easy. It was all in my language and the questions were very simple to understand. It’s my first time doing taxes in Switzerland.',
        cplH2Four: 'Were you skeptical about taxly in the beginning?',
        cplpFour: 'I don’t know. Everyone said doing taxes in Switzerland was complex and costly. But I found the opposite with Taxly.',
        cplH2Five: 'What was your favorite thing about Taxly?',
        cplpFive: 'How simple it was to do.',
        cplH2Six: 'Would you recommend Taxly to a friend?',
        cplpSix: 'Yes.',
    },
];

export { SingleData, CommunityStorySectionData };